version: '3'

services:
  ubuntu:
    image: local/ubuntu:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    # for interactive shell
    tty: true
    restart: always
    command: "/bin/bash"
    volumes:
      - .:/home/nonroot
